config/routes.rb
Rails.application.routes.draw do
	  post 'users/reg'
	  post 'users/demo'
	  get 'users/login'
	  get'users/index'
get'users/error'
get'users/admin'
get'users/register'

controller :sessions do
    delete 'logout' => :destroy
end
 root to: 'users#register'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def login


end
def destroy

   sessions[:user_id] = nil
   redirect_to users_login_path, :notice => "Log out"
  end 
def index 


	end
  def error
    @g = JSON.parse(RestClient.get('http://192.168.1.79:4021/emails/admin_panel').body)
  end
  def admin
    byebug
  @g = params["format"]



  
  end
  def register
  end
  def reg
  
  	@user = User.create(email: params[:user][:email],password: params[:user][:password],user_role: params[:user][:user_role])
    if @user.save
   redirect_to users_login_path 
    else
 	 render json: false
    end
  end


  def demo

@user = User.find_by(email: params[:user][:email],password: params[:user][:password])
    byebug
       if @user.user_role == "user"
        
         redirect_to users_index_path 
  	   elsif @user.user_role == "admin"
         redirect_to users_admin_path 
       else
         redirect_to users_error_path      
      end

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminePanel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/admin.html.erb
<h1>Admin page</h1><%= link_to 'Logout', users_login_path, method: :delete %>
<%= @g[0] %>

app/views/users/error.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<html>
<!--  <div data-role="page" id="pageone">
 --><table class="table table-striped table-sm table_front">
                                    
                                    <tbody>
                                        <% @g.each do |h| %> 
                                        
        
                     
                       
                                        <tr>
                          
                                  <td><%= h[0] %></td>
                                  <td><%= h[1] %></td>
                                  <td><%= h[2] %></td>
                                  <td><%= h[3] %></td>
                                  <td><%= h[4] %></td>
                                  
                                  <th> <%= link_to "click", users_admin_path(h[0])%>



                                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">View Details</button></th>
                                      </tr>
 <% end %>
                                    </tbody>
                                </table>
<body>
 <div class="container">
  <div class="modal" id="myModal" >
    <div class="modal-dialog">
      <div class="modal-content">
      
        <div class="modal-header">
          <h4 class="modal-title">User Details</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <table class="table table-striped">
                                  
                                    <tbody>
                                        <% @g.each do |h| %> 
                             
                                        <tr>
                          
                                  <td><%= h[5] %></td>
                                  <td><%= h[6] %></td>
                                  <td><%= h[7] %></td>
                                  <td><%= h[8] %></td>
                                  <td><%= h[9] %></td>
                                  <td><%= h[10] %></td>
                                  <td><%= h[11] %></td>
                                  <td><%= h[12] %></td>
                                  <td><%= h[13] %></td>


                                      </tr>
 <% end %>
                                    </tbody>
                                </table>

        
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
  
</div>
 



  
 <!--   <div data-role="main" class="ui-content">
    <div data-role="collapsible">
      <h1>Click me - I'm collapsible!</h1>
      <p>I'm the expanded content.</p>
    </div>
  </div>
 
  </div>  -->


</body>
</html>

app/views/users/index.html.erb
<!-- 

<!DOCTYPE html>

<html>


<body>

​
 -->
<h2>Report</h2>  <%= link_to('Logout', users_login_path, method: :delete) %>  


​

<table class="table table-bordered">

  <tr>

    <th>Name</th>

    <th>Email</th>

    <th>Phone_no</th>
    <th>Camp_count</th>
    <th>Promo_count</th>
    <th>Order_count</th>
    <th>Cancel</th>
    <th>Shipped</th>
    <th>Pending</th>
    <th>Unshipped</th>
    <th>Camp_send</th>
    <th>Camp_scheduled</th>
    <th>Promo_send</th>
    <th>Promo_scheduled</th>

  </tr>
  <tr>
<td>wrwrwr</td></tr>
</table>

​

app/views/users/login.html.erb

<div class="row">
<div class="col-md-5">
  
</div>


<div class="col-md-2" style="text-align: center;"> 
 <h2 >Login</h2>
 <%= form_for :user,url: { action: "demo" },method: :post do |f| %>
   <div class="form-group">
     <%= f.label :email %><br>
  <%= f.text_field :email, class: "form-control" ,type: "email", placeholder: "Enter your E-Mail" %> 

  </div>

  

 <div class="form-group">
      <%= f.label :password %><br>
  <%= f.text_field :password, class: "form-control", type: "password" ,placeholder: "Enter your password" %> 

  </div>

  <!-- <div class="form-group">
      <%= f.label :user_role  %><br>

<select name="user[user_role]" id="user_user_role"  class="form-control" style="width: 215px;">
<option value="">Select Role</option>
  <option value="user">user</option>
<option value="admin">admin</option></select>


  </div>
 -->

  <%= f.submit "Log in", class: "btn btn-info" %>  <br><br>
  Create New Account?<br>
  <%= link_to "Register",users_register_path %>

 <!--  <button class="btn btn-info"><%= link_to "sign in", users_index_path, method: :post, data: { confirm: "Login Sucessfull?" } %>
   </button><% end %>
</div> -->
<div class="col-md-5">
  
</div>


</div>

app/views/users/register.html.erb
  

<body class="row" >
<div class="col-md-5">
  
</div>


<div class="col-md-2"> 
 <h2 >Register</h2>
 <%= form_for :user,url: { action: "reg" },method: :post do |f| %>
  

  <div class="form-group">
     <%= f.label :email %><br>
  <%= f.text_field :email, class: "form-control" ,type: "email",placeholder: "Enter your E-Mail" %> 

  </div>

  <div class="form-group">
      <%= f.label :password %><br>
  <%= f.text_field :password, class: "form-control", type: "password",placeholder: "Enter your Password" %> 

  </div>
  <div class="form-group">
      <%= f.label :user_role  %><br>
  <select name="user[user_role]" id="user_user_role"  class="form-control" style="width: 215px;">
<option value="">Select Role</option>
  <option value="user">user</option>
<option value="admin">admin</option>
</select>
</div>

 
 <%= f.submit "Register", class: "btn btn-info" %>  <br>
 <br>
Already have an account?<br>
 <%= link_to "sign in",users_login_path %>
<!--   <button class="btn btn-info">sign in</button>
 -->   <% end %>
</div>
<div class="col-md-5"></div>

</body>